### ISSUE TITLE
Missing storage key ?

### ISSUE THREAD

**Issue by jorisd** [Azure-Samples/functions-dotnet-sas-token#4]
Hi,
Although you state in the readme that one needs Storage keys to generate a SAS, I don't see any use of them in your Function.
How is that supposed to work ?

**Comment by jorisd** [comment]
OK, now I get it.
You fetch it here : https://github.com/Azure-Samples/functions-dotnet-sas-token/blob/master/GetSasToken-Net/run.csx#L37

**Comment by dpaanlka** [comment]
Would you be able to elaborate on this? I’m not seeing the answer on Line 37 but I’m not even 100% sure what to look for.
